### PR TITLE
Add compatibility symfony 3

### PR DESCRIPTION
**Pull request by Discutea**

### CODE REVIEW

**Comment by azine** [comment]
Thanx for your work!

**Comment by Discutea** [comment]
You're welcome

Please wait before creating a new tag for packagist i would like to finish trying everything and add the french language.

Is it possible that I fix some siensoinsight sujestions?

https://insight.sensiolabs.com/projects/91c40edd-e95a-418c-b88a-b1c0d97ed594/analyses/1

**Comment by azine** [comment]
You are more than welcome to do so! :-) 

Just let me know when you're ready for a review and the tagging.

**Comment by Discutea** [comment]
Ok, Thanx

**Pull request merged**
